-- Question 5: Ranking and Analytics
-- Rank products within each ProductSubcategoryID based on their total revenue.
-- Include ProductID, Name, TotalRevenue, and RankWithinSubcategory.
-- Bonus: Calculate the percentage difference in revenue between the current product and the top-ranked product in its subcategory.

-- Step 1: Aggregate total revenue for each product.
WITH ProductRevenue AS (
    SELECT 
        sod.ProductID, -- Identifier of the product
        p.Name, -- Name of the product
        ps.ProductSubcategoryID, -- Subcategory ID of the product
        SUM(sod.LineTotal) AS TotalRevenue -- Total revenue generated by the product
    FROM 
        Sales.SalesOrderDetail sod
    JOIN 
        Production.Product p ON sod.ProductID = p.ProductID
    JOIN 
        Production.ProductSubcategory ps ON p.ProductSubcategoryID = ps.ProductSubcategoryID
    GROUP BY 
        sod.ProductID, 
        p.Name, 
        ps.ProductSubcategoryID
),
-- Step 2: Rank products within each subcategory by total revenue and calculate the top revenue in each subcategory.
RankedProducts AS (
    SELECT 
        ProductID, 
        Name, 
        ProductSubcategoryID,
        TotalRevenue,
        RANK() OVER (PARTITION BY ProductSubcategoryID ORDER BY TotalRevenue DESC) AS RankWithinSubcategory, -- Rank within subcategory
        MAX(TotalRevenue) OVER (PARTITION BY ProductSubcategoryID) AS TopRevenue -- Maximum revenue in the subcategory
    FROM 
        ProductRevenue
)
-- Step 3: Calculate the percentage difference between each product's revenue and the top-ranked product's revenue in its
SELECT 
    ProductID, 
    Name, 
    TotalRevenue,
    RankWithinSubcategory,
    (TopRevenue - TotalRevenue) * 100.0 / TopRevenue AS RevenuePercentageDifference
FROM 
    RankedProducts
ORDER BY 
    ProductSubcategoryID, 
    RankWithinSubcategory;
