-- Question 2: Complex Aggregation and Grouping
-- Step 1: Join SalesOrderDetail and Product tables to access product and sales data.
-- Step 2: Exclude subcategories with 'Bike' in their name.
-- Step 3: Use aggregation to compute total quantity sold and revenue for each ProductModelID.
-- Step 4: Calculate the percentage contribution of each ProductModelID to the overall revenue.

SELECT 
    p.ProductModelID, -- Product model identifier
    SUM(sod.OrderQty) AS TotalQuantitySold, -- Total quantity sold for the product model
    SUM(sod.LineTotal) AS TotalRevenue, -- Total revenue generated by the product model
    SUM(sod.LineTotal) * 100.0 / SUM(SUM(sod.LineTotal)) OVER () AS RevenuePercentage -- Revenue percentage of the model
FROM 
    Sales.SalesOrderDetail sod
JOIN 
    Production.Product p ON sod.ProductID = p.ProductID
JOIN 
    Production.ProductSubcategory ps ON p.ProductSubcategoryID = ps.ProductSubcategoryID
WHERE 
    p.ProductModelID IS NOT NULL -- Ensure ProductModelID is valid
    AND ps.Name NOT LIKE '%Bike%' -- Exclude subcategories with 'Bike' in their name
GROUP BY 
    p.ProductModelID
HAVING 
    SUM(sod.OrderQty) > 1000; -- Include only products with total sales greater than 1000
GO